In [1]:
import pandas as pd

In [2]:
# Read in data
drinks_content = pd.read_csv("data/starbucks_drinkMenu_expanded.csv")
drinks_content.head()

,Beverage_category,Beverage,Beverage_prep,Calories,Total Fat (g),Trans Fat (g),Saturated Fat (g),Sodium (mg),Total Carbohydrates (g),Cholesterol (mg),Dietary Fibre (g),Sugars (g),Protein (g),Vitamin A (% DV),Vitamin C (% DV),Calcium (% DV),Iron (% DV),Caffeine (mg)
0,Coffee,Brewed Coffee,Short,3,0.1,0.0,0.0,0,5,0,0,0,0.3,0%,0%,0%,0%,175
1,Coffee,Brewed Coffee,Tall,4,0.1,0.0,0.0,0,10,0,0,0,0.5,0%,0%,0%,0%,260
2,Coffee,Brewed Coffee,Grande,5,0.1,0.0,0.0,0,10,0,0,0,1.0,0%,0%,0%,0%,330
3,Coffee,Brewed Coffee,Venti,5,0.1,0.0,0.0,0,10,0,0,0,1.0,0%,0%,2%,0%,410
4,Classic Espresso Drinks,Caffè Latte,Short Nonfat Milk,70,0.1,0.1,0.0,5,75,10,0,9,6.0,10%,0%,20%,0%,75

In [3]:
drinks_content.tail()

,Beverage_category,Beverage,Beverage_prep,Calories,Total Fat (g),Trans Fat (g),Saturated Fat (g),Sodium (mg),Total Carbohydrates (g),Cholesterol (mg),Dietary Fibre (g),Sugars (g),Protein (g),Vitamin A (% DV),Vitamin C (% DV),Calcium (% DV),Iron (% DV),Caffeine (mg)
237,Frappuccino® Blended Crème,Strawberries & Crème (Without Whipped Cream),Soymilk,320,3 2,0.4,0.0,0,250,67,1,64,5.0,6%,8%,20%,10%,0
238,Frappuccino® Blended Crème,Vanilla Bean (Without Whipped Cream),Tall Nonfat Milk,170,0.1,0.1,0.0,0,160,39,0,38,4.0,6%,0%,10%,0%,0
239,Frappuccino® Blended Crème,Vanilla Bean (Without Whipped Cream),Whole Milk,200,3.5,2.0,0.1,10,160,39,0,38,3.0,6%,0%,10%,0%,0
240,Frappuccino® Blended Crème,Vanilla Bean (Without Whipped Cream),Soymilk,180,1.5,0.2,0.0,0,160,37,1,35,3.0,4%,0%,10%,6%,0
241,Frappuccino® Blended Crème,Vanilla Bean (Without Whipped Cream),Grande Nonfat Milk,240,0.1,0.1,0.0,5,230,56,0,55,5.0,8%,0%,15%,0%,0

In [4]:
drinks_content

,Beverage_category,Beverage,Beverage_prep,Calories,Total Fat (g),Trans Fat (g),Saturated Fat (g),Sodium (mg),Total Carbohydrates (g),Cholesterol (mg),Dietary Fibre (g),Sugars (g),Protein (g),Vitamin A (% DV),Vitamin C (% DV),Calcium (% DV),Iron (% DV),Caffeine (mg)
0,Coffee,Brewed Coffee,Short,3,0.1,0.0,0.0,0,5,0,0,0,0.3,0%,0%,0%,0%,175
1,Coffee,Brewed Coffee,Tall,4,0.1,0.0,0.0,0,10,0,0,0,0.5,0%,0%,0%,0%,260
2,Coffee,Brewed Coffee,Grande,5,0.1,0.0,0.0,0,10,0,0,0,1.0,0%,0%,0%,0%,330
3,Coffee,Brewed Coffee,Venti,5,0.1,0.0,0.0,0,10,0,0,0,1.0,0%,0%,2%,0%,410
4,Classic Espresso Drinks,Caffè Latte,Short Nonfat Milk,70,0.1,0.1,0.0,5,75,10,0,9,6.0,10%,0%,20%,0%,75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
237,Frappuccino® Blended Crème,Strawberries & Crème (Without Whipped Cream),Soymilk,320,3 2,0.4,0.0,0,250,67,1,64,5.0,6%,8%,20%,10%,0
238,Frappuccino® Blended Crème,Vanilla Bean (Without Whipped Cream),Tall Nonfat Milk,170,0.1,0.1,0.0,0,160,39,0,38,4.0,6%,0%,10%,0%,0
239,Frappuccino® Blended Crème,Vanilla Bean (Without Whipped Cream),Whole Milk,200,3.5,2.0,0.1,10,160,39,0,38,3.0,6%,0%,10%,0%,0
240,Frappuccino® Blended Crème,Vanilla Bean (Without Whipped Cream),Soymilk,180,1.5,0.2,0.0,0,160,37,1,35,3.0,4%,0%,10%,6%,0
241,Frappuccino® Blended Crème,Vanilla Bean (Without Whipped Cream),Grande Nonfat Milk,240,0.1,0.1,0.0,5,230,56,0,55,5.0,8%,0%,15%,0%,0

In [5]:
drinks_content.shape

(242, 18)

In [6]:
drinks_content.columns

Index(['Beverage_category', 'Beverage', 'Beverage_prep', 'Calories',
       ' Total Fat (g)', 'Trans Fat (g) ', 'Saturated Fat (g)', ' Sodium (mg)',
       ' Total Carbohydrates (g) ', 'Cholesterol (mg)', ' Dietary Fibre (g)',
       ' Sugars (g)', ' Protein (g) ', 'Vitamin A (% DV) ', 'Vitamin C (% DV)',
       ' Calcium (% DV) ', 'Iron (% DV) ', 'Caffeine (mg)'],
      dtype='object')

In [8]:
drinks_content_copy = drinks_content.copy()

## 2. We're going to be looking at the number of Calories in each drink. Calculate some quick summary statistics (e.g. the mean, the maximum and minimum).

In [7]:
drinks_content.describe()

,Calories,Trans Fat (g),Saturated Fat (g),Sodium (mg),Total Carbohydrates (g),Cholesterol (mg),Dietary Fibre (g),Sugars (g),Protein (g)
count,242.000000,242.000000,242.000000,242.000000,242.000000,242.000000,242.000000,242.000000,242.000000
mean,193.871901,1.307025,0.037603,6.363636,128.884298,35.991736,0.805785,32.962810,6.978512
std,102.863303,1.640259,0.071377,8.630257,82.303223,20.795186,1.445944,19.730199,4.871659
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,120.000000,0.100000,0.000000,0.000000,70.000000,21.000000,0.000000,18.000000,3.000000
50%,185.000000,0.500000,0.000000,5.000000,125.000000,34.000000,0.000000,32.000000,6.000000
75%,260.000000,2.000000,0.100000,10.000000,170.000000,50.750000,1.000000,43.750000,10.000000
max,510.000000,9.000000,0.300000,40.000000,340.000000,90.000000,8.000000,84.000000,20.000000

In [9]:
drinks_content.groupby("Beverage_category").mean()

C:\Users\slhen\AppData\Local\Temp\ipykernel_25340\1034537945.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  drinks_content.groupby("Beverage_category").mean()

,Calories,Trans Fat (g),Saturated Fat (g),Sodium (mg),Total Carbohydrates (g),Cholesterol (mg),Dietary Fibre (g),Sugars (g),Protein (g)
Beverage_category,,,,,,,,,
Classic Espresso Drinks,140.172414,1.210345,0.046552,8.103448,104.672414,20.327586,0.620690,16.965517,8.686207
Coffee,4.250000,0.000000,0.000000,0.000000,8.750000,0.000000,0.000000,0.000000,0.700000
Frappuccino® Blended Coffee,276.944444,1.700000,0.038889,4.444444,230.277778,59.638889,0.777778,57.083333,4.222222
Frappuccino® Blended Crème,233.076923,0.769231,0.038462,4.230769,188.846154,49.923077,0.307692,48.461538,4.000000
Frappuccino® Light Blended Coffee,162.500000,0.900000,0.000000,1.666667,217.500000,34.500000,0.666667,32.416667,4.250000
Shaken Iced Beverages,114.444444,0.138889,0.005556,1.111111,18.277778,26.166667,0.000000,26.000000,1.344444
Signature Espresso Drinks,250.000000,2.712500,0.050000,9.625000,138.250000,42.775000,0.775000,38.600000,9.875000
Smoothies,282.222222,0.933333,0.011111,6.111111,132.777778,54.555556,6.777778,36.777778,17.111111
Tazo® Tea Drinks,177.307692,0.859615,0.044231,7.211538,89.903846,31.692308,0.519231,30.307692,6.807692

## 3: Select the variables Beverage_category, Beverage, Beverage prep and Calories from the drinks_content data frame, and assign the selected columns to a new data frame called drinks. Check if there are any missing values anywhere in the data, and drop any rows containing them if there are.

In [12]:
drinks = drinks_content[["Beverage_category", "Beverage", "Beverage_prep","Calories"]]
drinks.head()

         Beverage_category       Beverage      Beverage_prep  Calories
0                   Coffee  Brewed Coffee              Short         3
1                   Coffee  Brewed Coffee               Tall         4
2                   Coffee  Brewed Coffee             Grande         5
3                   Coffee  Brewed Coffee              Venti         5
4  Classic Espresso Drinks    Caffè Latte  Short Nonfat Milk        70

In [13]:
drinks.isnull().any()

Beverage_category    False
Beverage             False
Beverage_prep        False
Calories             False
dtype: bool

## 4: In your drinks dataframe create a new variable (column) called calorie_diff, which stores the difference between 135 calories (135 calories = 10 cubes of sugar!) and the calories in each drink. (Hint: you’ll want to subtract the calories from 135 to see which drinks have more or less than 10 cubes of sugar).

In [16]:
drinks["calorie_diff"] = drinks["Calories"] - 135
drinks

C:\Users\slhen\AppData\Local\Temp\ipykernel_25340\3945723882.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  drinks["calorie_diff"] = drinks["Calories"] - 135

,Beverage_category,Beverage,Beverage_prep,Calories,calorie_diff
0,Coffee,Brewed Coffee,Short,3,-132
1,Coffee,Brewed Coffee,Tall,4,-131
2,Coffee,Brewed Coffee,Grande,5,-130
3,Coffee,Brewed Coffee,Venti,5,-130
4,Classic Espresso Drinks,Caffè Latte,Short Nonfat Milk,70,-65
...,...,...,...,...,...
237,Frappuccino® Blended Crème,Strawberries & Crème (Without Whipped Cream),Soymilk,320,185
238,Frappuccino® Blended Crème,Vanilla Bean (Without Whipped Cream),Tall Nonfat Milk,170,35
239,Frappuccino® Blended Crème,Vanilla Bean (Without Whipped Cream),Whole Milk,200,65
240,Frappuccino® Blended Crème,Vanilla Bean (Without Whipped Cream),Soymilk,180,45
241,Frappuccino® Blended Crème,Vanilla Bean (Without Whipped Cream),Grande Nonfat Milk,240,105

## 5: Summarise the mean number of calories in each beverage category.

In [17]:
drinks.groupby("Beverage_category").mean()

C:\Users\slhen\AppData\Local\Temp\ipykernel_25340\2988503421.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  drinks.groupby("Beverage_category").mean()

                                     Calories  calorie_diff
Beverage_category
Classic Espresso Drinks            140.172414      5.172414
Coffee                               4.250000   -130.750000
Frappuccino® Blended Coffee        276.944444    141.944444
Frappuccino® Blended Crème         233.076923     98.076923
Frappuccino® Light Blended Coffee  162.500000     27.500000
Shaken Iced Beverages              114.444444    -20.555556
Signature Espresso Drinks          250.000000    115.000000
Smoothies                          282.222222    147.222222
Tazo® Tea Drinks                   177.307692     42.307692

## 6: Harder - Which Beverage_prep type contains more than the average calories of all drinks? (Hint: to answer this, you’ll have to first figure out what the average calories across all drinks are, and then use that as a filter for the grouped Beverage_prep data).

In [18]:
drinks["Calories"].mean()

193.87190082644628

In [25]:
drinks_prep_group = drinks.groupby("Beverage_prep").mean()
drinks_prep_group[drinks_prep_group["Calories"]>drinks["Calories"].mean()]

C:\Users\slhen\AppData\Local\Temp\ipykernel_25340\1477868208.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  drinks_prep_group = drinks.groupby("Beverage_prep").mean()

                      Calories  calorie_diff
Beverage_prep
2% Milk             218.000000     83.000000
Grande Nonfat Milk  209.615385     74.615385
Soymilk             207.272727     72.272727
Venti Nonfat Milk   260.000000    125.000000
Whole Milk          283.750000    148.750000

## 7: Harder - Which is the best type of coffee drink to get if you’re worried about consuming too many calories? (Hint: you can use pd.unique() on a column to get all unique values/levels of that column! Also remember that you can use isin() to subset with a list)

In [28]:
drinks["Beverage_category"].unique()

array(['Coffee', 'Classic Espresso Drinks', 'Signature Espresso Drinks',
       'Tazo® Tea Drinks', 'Shaken Iced Beverages', 'Smoothies',
       'Frappuccino® Blended Coffee', 'Frappuccino® Light Blended Coffee',
       'Frappuccino® Blended Crème'], dtype=object)

In [41]:
drinks[drinks["Beverage_category"].isin(["Coffee", "Espresso"])]

  Beverage_category       Beverage Beverage_prep  Calories  calorie_diff
0            Coffee  Brewed Coffee         Short         3          -132
1            Coffee  Brewed Coffee          Tall         4          -131
2            Coffee  Brewed Coffee        Grande         5          -130
3            Coffee  Brewed Coffee         Venti         5          -130

## 8: Filter the dataset drinks so we only take "Classic Espresso Drinks", and save this in a new data frame called espresso_drinks.

In [43]:
espresso_drinks = drinks[drinks["Beverage_category"] == "Classic Espresso Drinks"]
espresso_drinks.head(8)

,Beverage_category,Beverage,Beverage_prep,Calories,calorie_diff
4,Classic Espresso Drinks,Caffè Latte,Short Nonfat Milk,70,-65
5,Classic Espresso Drinks,Caffè Latte,2% Milk,100,-35
6,Classic Espresso Drinks,Caffè Latte,Soymilk,70,-65
7,Classic Espresso Drinks,Caffè Latte,Tall Nonfat Milk,100,-35
8,Classic Espresso Drinks,Caffè Latte,2% Milk,150,15
9,Classic Espresso Drinks,Caffè Latte,Soymilk,110,-25
10,Classic Espresso Drinks,Caffè Latte,Grande Nonfat Milk,130,-5
11,Classic Espresso Drinks,Caffè Latte,2% Milk,190,55

## 9: Group your espresso_drinks data frame by the type of Beverage prep, and then find out the mean calories for each drink group.

In [44]:
espresso_drinks.groupby("Beverage_prep").mean()

C:\Users\slhen\AppData\Local\Temp\ipykernel_25340\3352057521.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  espresso_drinks.groupby("Beverage_prep").mean()

                    Calories  calorie_diff
Beverage_prep
2% Milk              184.375        49.375
Doppio                10.000      -125.000
Grande                15.000      -120.000
Grande Nonfat Milk   150.000        15.000
Short                  5.000      -130.000
Short Nonfat Milk     78.000       -57.000
Solo                   5.000      -130.000
Soymilk              151.250        16.250
Tall                  10.000      -125.000
Tall Nonfat Milk     116.000       -19.000
Venti                 25.000      -110.000
Venti Nonfat Milk    194.000        59.000

## 10: Get the same grouped mean Calories values as above, but this time sorted in descending order. (Hint: so you're able to sort the resulting groupby by the 'Calories' column you will want to ensure you get back a dataframe and not a series)

In [45]:
espresso_grouped = espresso_drinks.groupby("Beverage_prep").mean()
espresso_grouped.sort_values("Calories")

C:\Users\slhen\AppData\Local\Temp\ipykernel_25340\3909718536.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  espresso_grouped = espresso_drinks.groupby("Beverage_prep").mean()

                    Calories  calorie_diff
Beverage_prep
Short                  5.000      -130.000
Solo                   5.000      -130.000
Doppio                10.000      -125.000
Tall                  10.000      -125.000
Grande                15.000      -120.000
Venti                 25.000      -110.000
Short Nonfat Milk     78.000       -57.000
Tall Nonfat Milk     116.000       -19.000
Grande Nonfat Milk   150.000        15.000
Soymilk              151.250        16.250
2% Milk              184.375        49.375
Venti Nonfat Milk    194.000        59.000

## Extension: Now, play around with the data yourself. Is there anything in the data? Any interesting plots you can make?

In [53]:
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'matplotlib.artist'

In [52]:
import seaborn as sns

ModuleNotFoundError: No module named 'matplotlib.artist'

In [50]:
drinks_means = drinks.groupby("Beverage_category").mean()
drinks_means

C:\Users\slhen\AppData\Local\Temp\ipykernel_25340\4028522159.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  drinks_means = drinks.groupby("Beverage_category").mean()

                                     Calories  calorie_diff
Beverage_category
Classic Espresso Drinks            140.172414      5.172414
Coffee                               4.250000   -130.750000
Frappuccino® Blended Coffee        276.944444    141.944444
Frappuccino® Blended Crème         233.076923     98.076923
Frappuccino® Light Blended Coffee  162.500000     27.500000
Shaken Iced Beverages              114.444444    -20.555556
Signature Espresso Drinks          250.000000    115.000000
Smoothies                          282.222222    147.222222
Tazo® Tea Drinks                   177.307692     42.307692

In [54]:
plt.barplot(x = "Beverage_category", y = "Calories", data = drinks_means);

NameError: name 'plt' is not defined